# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint as rd

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 
numeros = np.arange(10) # el arange crea un array de 0 a 9
print(numeros)


[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo:
numeros = np.zeros(5) # el zeros crea un array de 0s de tamaño 5

print(f"array con los numeros normales {numeros}")

#Cambiamos el valor del tercer elemento

numeros[2] = 5
print(f"array con el tercer elemento modificado {numeros}")

array con los numeros normales [0. 0. 0. 0. 0.]
array con el tercer elemento modificado [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [ ]:
#todo: 
matriz= np.random.randint(1,10, (3, 3)) # crea una matriz de 3x3 con valores aleatorios entre 1 y 10
print("Matriz de 3x3")
print(matriz)


Matriz de 3x3
[[6 5 9]
 [9 1 9]
 [5 2 9]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [2]:
#todo:
arr=np.array([10,20,30,40,50])
print(f"Array original {arr}")


arr_suma5 = arr + 5 # suma 5 a cada elemento del array
print(f"Array con 5 sumado a cada elemento {arr_suma5}")

numero_random = rd(0,10) # genera un numero aleatorio entre 0 y 10
print(f"Numero aleatorio {numero_random}")

arr_multiplicacion = arr * numero_random # multiplica cada elemento del array por el numero aleatorio

print(f"Array multiplicado por el numero aleatorio {arr_multiplicacion}")




Array original [10 20 30 40 50]
Array con 5 sumado a cada elemento [15 25 35 45 55]
Numero aleatorio 8
Array multiplicado por el numero aleatorio [ 80 160 240 320 400]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
Matriz_identidad=np.identity(4) # crea una matriz identidad de 4x4
print(f"Matriz identidad de 4x4 \n {Matriz_identidad}") 

Matriz identidad de 4x4 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [20]:
#todo: 

#Haciendo las operaciones entre si
array_pares = np.arange(0,20 ,2) # crea un array de 0 a 20 con pasos de 2
print(f"Array sin modificaciones {array_pares}")

Suma_entre_si = np.sum(array_pares) # suma todos los elementos del array
print(f"Suma de todos los elementos del array {Suma_entre_si}")

resta_entre_si = np.subtract(array_pares, 4) # resta 4 a cada elemento del array
print(f"Resta de todos los elementos del array {resta_entre_si}")

multiplicacion_entre_si = np.prod(array_pares[array_pares != 0]) # multiplica todos los elementos del array evitando el 0
print(f"Multiplicacion de todos los elementos del array {multiplicacion_entre_si}")

division_entre_si = array_pares[:-1] / array_pares[1:] # array dividiendo cada elemento por el siguiente (excepto el último)
print(f"Division de todos los elementos del array {division_entre_si}")

print(" \n haciendo las operaciones con un numero ingresado por mi \n ")

#Haciendo las operaciones con el numero "2"

suma_2 = array_pares + 2
resta_2 = array_pares - 2
multiplicacion_2 = array_pares * 2
division_2 = array_pares / 2

print(f"Suma (+2): {suma_2} ")
print(f"Resta (-2): {resta_2} ")
print(f"Multiplicación (*2): {multiplicacion_2}")
print(f"División (/2): {division_2} ")

Array sin modificaciones [ 0  2  4  6  8 10 12 14 16 18]
Suma de todos los elementos del array 90
Resta de todos los elementos del array [-4 -2  0  2  4  6  8 10 12 14]
Multiplicacion de todos los elementos del array 185794560
Division de todos los elementos del array [0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889]
 
 haciendo las operaciones con un numero ingresado por mi 
 
Suma (+2): [ 2  4  6  8 10 12 14 16 18 20] 
Resta (-2): [-2  0  2  4  6  8 10 12 14 16] 
Multiplicación (*2): [ 0  4  8 12 16 20 24 28 32 36]
División (/2): [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 
